### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Aspasht** [BishopFox/jsluice#11]
I'm getting this error message while installing. I've node installed and go is also properly configured. 
```
# github.com/smacker/go-tree-sitter
../../go/pkg/mod/github.com/smacker/go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11/iter.go:17:18: undefined: Node
../../go/pkg/mod/github.com/smacker/go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11/iter.go:21:21: undefined: Node
../../go/pkg/mod/github.com/smacker/go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11/iter.go:25:20: undefined: Node
../../go/pkg/mod/github.com/smacker/go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11/iter.go:30:26: undefined: Node
../../go/pkg/mod/github.com/smacker/go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11/iter.go:34:20: undefined: Node
../../go/pkg/mod/github.com/smacker/go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11/iter.go:38:32: undefined: Node
../../go/pkg/mod/github.com/smacker/go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11/iter.go:43:9: undefined: Node
../../go/pkg/mod/github.com/smacker/go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11/iter.go:46:18: undefined: Node
../../go/pkg/mod/github.com/smacker/go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11/iter.go:68:40: undefined: Node
github.com/smacker/go-tree-sitter/javascript: build constraints exclude all Go files in /home/ubuntu/go/pkg/mod/github.com/smacker/go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11/javascript
```

**Comment by nightshiba** [comment]
JFYI I have found a fix in katana issues (https://github.com/projectdiscovery/katana/issues/546), just had to install 2 packages:
`sudo apt-get install gcc musl-dev`
(https://github.com/projectdiscovery/katana/pull/547/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R2)

**Comment by rayep** [comment]
@nightshiba Any insights on how to fix this issue in Windows 11?
Thank you!

**Comment by 0x123456789** [comment]
Any ideas how to fix on Windows?

**Comment by rayep** [comment]
@0x123456789 I've fixed it by installing **gcc/g++** binary that comes with mingGW package.

In my case, I chose winlibs.com and downloaded this archive - https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0mcf-16.0.6-11.0.1-ucrt-r2/winlibs-x86_64-mcf-seh-gcc-13.2.0-llvm-16.0.6-mingw-w64ucrt-11.0.1-r2.7z

After download, extract it to any location (eg. C:\), add the **C:\mingw64\bin** to PATH environment variable, close and reopen the terminal/cmd and retry the jsluice installation.

Cheers! :)

**Comment by 0x123456789** [comment]
@rayep Thank you! I will try later if more simple solution doesn't appear

**Comment by bf-tomnomnom** [comment]
@0x123456789 were you able to resolve your issue?

**Comment by 0x123456789** [comment]
@bf-tomnomnom hi, solution suggested by @rayep working on Windows 11, thanks 🙂

**Comment by 0xsheet** [comment]
> @0x123456789 I've fixed it by installing **gcc/g++** binary that comes with mingGW package.
> 
> In my case, I chose winlibs.com and downloaded this archive - https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0mcf-16.0.6-11.0.1-ucrt-r2/winlibs-x86_64-mcf-seh-gcc-13.2.0-llvm-16.0.6-mingw-w64ucrt-11.0.1-r2.7z
> 
> After download, extract it to any location (eg. C:), add the **C:\mingw64\bin** to PATH environment variable, close and reopen the terminal/cmd and retry the jsluice installation.
> 
> Cheers! :)

after two day is resolve this thanx bro !
