### ISSUE TITLE
support baseURL detect 

### ISSUE THREAD

**Issue by XTeam-Wing** [BishopFox/jsluice#26]
## Overview
Many current Vue and React sites may have baseURL setup. You need to splice the baseURL with the url inside the js to make the full url

<img width="420" alt="image" src="https://github.com/BishopFox/jsluice/assets/25416365/d7d1316f-6fd7-431a-990f-ca0b9cc9ed97">

## Acceptance Criteria
- Automatically recognizes baseURL and performs urljoin

#### Screenshots / Files

<img width="425" alt="image" src="https://github.com/BishopFox/jsluice/assets/25416365/42e4fc6e-5b51-4ca8-ae69-e1828f7e9b9d">

**Comment by XTeam-Wing** [comment]
<img width="458" alt="image" src="https://github.com/BishopFox/jsluice/assets/25416365/d5681d0a-8943-4d8f-9dd9-785453a0ac6e">

more case

**Comment by Gby56** [comment]
Hi @XTeam-Wing , did you make any progress by any chance on that subject ?

**Comment by XTeam-Wing** [comment]
> Hi @XTeam-Wing , did you make any progress by any chance on that subject ?

I'm blasting baseurl.
