### ISSUE TITLE
type jsluice.object has no field or method getKeys

### ISSUE THREAD

**Issue by YouGina** [BishopFox/jsluice#4]
When I try to use jsluice as a package I get the error message: `type jsluice.object has no field or method getKeys` when I do something like:

```go
secondArg := arguments.NamedChild(1)
if secondArg.Type() == "object" {
    params := secondArg.AsObject().getKeys()
    m.Method = "POST"
    m.BodyParams = params
} 
```
I've used [url-match-jquery.go](https://github.com/BishopFox/jsluice/blob/main/url-match-jquery.go) as a reference to create a custom url matcher for a project that uses a custom function to call api endpoints.

I likely am doing something wrong myself as I do not have that much experience with go, what could be the problem here?

**Comment by bf-tomnomnom** [comment]
Hey @YouGina! Thank you for raising an issue!

This looks to be an oversight on my part with not exporting some of the types that `jsluice` uses internally.

As of [this commit](https://github.com/BishopFox/jsluice/commit/ab7c68e5cf6a6cf17d157f1efdb18a83846577af), you should be able to call `secondArg.AsObject().GetKeys()` (note the capital `G` on `GetKeys`).

Thanks for bringing this to my attention!

**Comment by YouGina** [comment]
Hi @bf-tomnomnom , thank you for taking the time to look into this issue!
